
search_vehicles:
  description: Search for miles vehicles around a home assistant location or a given lat, lon coordinate
  fields:
    location:
      description: Name of the location in home assistant with a lat, lon entry
    latitude: 
      description: Latitude of the location
      example: 51.5074
    longitude:
      description: Longitude of the location
      example: 0.1278
    distance_meters:
      description: Radius in meters to search for vehicles
      example: 1000
    type_limit:
      description: Limit the search to a specific vehicle type
      example: ["S", "M", "L", "P"]
    gas_only:
      description: Only return vehicles with gas engines
      example: true
    electric_only:
      description: Only return vehicles with electric engines
      example: true

  
